version: '3.8'

services:
  account-db-service:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: account-db
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"

  nginx-lb-terminal:
    image: nginx:latest
    depends_on:
      - terminal-transaction-docker-service
    ports:
      - "81:80"
    volumes:
      - ./TerminalTransactionVerificationService/nginx.conf:/etc/nginx/nginx.conf:ro

  terminal-transaction-docker-service:
    image: "terminal-transaction-service_image"
    depends_on:
        - account-db-service