version: '3.8'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - web-transaction-docker-service
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  web-transaction-docker-service:
    image: "web-transaction-service_image"
