version: '3.8'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - terminal-transaction-docker-service
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  terminal-transaction-docker-service:
    image: "terminal-transaction-service_image"
